gallery.settings.gallery_slick:
  type: mapping
  label: 'Slick Carousel'
  mapping:
    accessibility:
      type: boolean
      label: 'accessibility'
    adaptive_height:
      type: boolean
      label: 'adaptiveHeight'
    autoplay:
      type: boolean
      label: 'autoplay'
    autoplay_speed:
      type: integer
      label: 'autoplayautoplaySpeed'
    arrows:
      type: boolean
      label: 'arrows'
    as_nav_for:
      type: string
      label: 'asNavFor'
    append_arrows:
      type: string
      label: 'appendArrows'
    append_dots:
      type: string
      label: 'appendDots'
    prev_arrow:
      type: text
      label: 'prevArrow'
    next_arrow:
      type: text
      label: 'nextArrow'
    center_mode:
      type: boolean
      label: 'centerMode'
    center_padding:
      type: string
      label: 'centerPadding'
    css_ease:
      type: string
      label: 'cssEase'
    custom_paging:
      type: string
      label: 'customPaging'
    dots:
      type: boolean
      label: 'dots'
    dots_class:
      type: string
      label: 'dotsClass'
    draggable:
      type: boolean
      label: 'draggable'
    fade:
      type: boolean
      label: 'fade'
    focus_on_select:
      type: boolean
      label: 'focusOnSelect'
    easing:
      type: string
      label: 'Easing'
    edge_friction:
      type: float
      label: 'edgeFriction'
    infinite:
      type: boolean
      label: 'infinite'
    initial_slide:
      type: integer
      label: 'initialSlide'
    lazy_load:
      type: string
      label: 'lazyLoad'
    mobile_first:
      type: boolean
      label: 'mobileFirst'
    pause_on_focus:
      type: boolean
      label: 'PausepauseOnFocus'
    pause_on_hover:
      type: boolean
      label: 'pauseOnHover'
    pause_on_dots_hover:
      type: boolean
      label: 'PausepauseOnDotsHover'
    respond_to:
      type: string
      label: 'respondTo'
    responsive:
      type: text
      label: 'responsive'
    rows:
      type: integer
      label: 'rows'
    slide:
      type: string
      label: 'slide'
    slides_per_row:
      type: integer
      label: 'slidesPerRow'
    slides_to_show:
      type: integer
      label: 'slidesToShow'
    slides_to_scroll:
      type: integer
      label: 'slidesToScroll'
    speed:
      type: integer
      label: 'Speed'
    swipe:
      type: boolean
      label: 'swipe'
    swipe_to_slide:
      type: boolean
      label: 'swipeToSlide'
    touch_move:
      type: boolean
      label: 'touchMove'
    touch_threshold:
      type: integer
      label: 'touchThreshold'
    use_css:
      type: boolean
      label: 'useCSS'
    use_transform:
      type: boolean
      label: 'useTransform'
    variable_width:
      type: boolean
      label: 'variableWidth'
    vertical:
      type: boolean
      label: 'Vertical'
    vertical_swiping:
      type: boolean
      label: 'verticalSwiping'
    rtl:
      type: boolean
      label: 'RTL'
    wait_for_animate:
      type: boolean
      label: 'waitForAnimate'
    z_index:
      type: integer
      label: 'zIndex'
