<?php

/**
 * @file
 * Provides Slick Carousel gallery plugin integration.
 */

/**
 * Implements hook_theme().
 */
function gallery_slick_theme($existing, $type, $theme, $path) {
  $path = $path . '/templates';
  return array(
    'gallery_slick' => array(
      'render element' => 'elements',
      'path' => $path,
      'file' => 'gallery_slick.theme.inc',
    ),
    'gallery_slick_slider' => array(
      'variables' => array(
        'slides' => array(),
        'attributes' => array(),
      ),
      'path' => $path,
      'file' => 'gallery_slick.theme.inc',
    ),
    'gallery_slick_slide' => array(
      'variables' => array(
        'slide' => NULL,
      ),
      'path' => $path,
      'file' => 'gallery_slick.theme.inc',
    ),
    'gallery_slick_nav_slider' => array(
      'variables' => array(
        'slides' => array(),
      ),
      'path' => $path,
      'file' => 'gallery_slick.theme.inc',
    ),
  );
}
