# Schema for the gallery config entity.

gallery.style.*:
  type: config_entity
  label: 'Gallery style'
  mapping:
    name:
      type: string
    uuid:
      type: string
      label: 'UUID'
    label:
      type: label
      label: 'Label'
    style:
      type: string
    settings:
      type: gallery.settings.[%parent.style]

gallery.settings.*:
  type: mapping
  label: 'Gallery settings'

