# Schema for the configuration files of the Mason module.

# Mason JS settings managed by UI.
mason_optionset:
  type: mapping
  label: 'Options'
  mapping:
    debug:
      type: boolean
      label: 'Debug'
    gutter:
      type: integer
      label: 'Gutter'
    itemSelector:
      type: string
      label: 'Item selector'
    layout:
      type: string
      label: 'Layout'
    randomSizes:
      type: boolean
      label: 'Random sizes'
    randomFillers:
      type: boolean
      label: 'Random fillers'
    ratio:
      type: integer
      label: 'Ratio'
    columns:
      type: sequence
      label: 'Columns'
      sequence:
        type: string
    promoted:
      type: sequence
      label: 'Promoted'
      sequence:
        type: string
    sizes:
      type: sequence
      label: 'Sizes'
      sequence:
        type: string
    filler:
      type: mapping
      label: 'Filler'
      mapping:
        itemSelector:
          type: string
          label: 'Item selector'
        filler_class:
          type: string
          label: 'Filler class'
        keepDataAndEvents:
          type: boolean
          label: 'Keep Data and Events'

# Individual Mason JS settings managed by UI.
mason.optionset.*:
  type: config_entity
  label: 'Mason optionset'
  mapping:
    id:
      type: string
      label: 'ID'
    name:
      type: string
      label: 'Name'
    weight:
      type: integer
      label: 'Weight'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
      label: 'UUID'
    json:
      type: string
      label: 'Json'
    options:
      type: mason_optionset
      label: 'Options'


# HTML content/layout-related settings managed by Mason plugins.
mason_base:
  type: blazy_base
  label: 'Mason display format base settings'
  mapping:
    caption:
      type: sequence
      label: 'Captions'
      sequence:
        - type: string
          label: 'Caption field'
    fillers:
      type: integer
      label: 'Filler start at'
    lazyload:
      type: string
      label: 'Lazy load'
    stamp:
      type: sequence
      label: 'Stamps'
      sequence:
        - type: string

views.style.mason:
  type: mason_base
  label: 'Mason'
  mapping:
    id:
      type: string
      label: 'Mason ID'
